### ISSUE TITLE
課題レビュー

### ISSUE THREAD

**Issue by kuwabaras** [HirokiMAEDA-TC/webjava_2#1]
大変遅くなりましたが以下、レビュー指摘になります。
・まずは動作的には問題ないです。一通り実装できていて素晴らしいです。
・ただ、作り方の点で指定と異なる点があります。
　職業に応じて戦士クラスや魔法使いクラスをインスタンス化していますが、それはキャラクター情報としてセッションに保存してください。（Characterクラスに名称のJobを持っていますが、それを置き換えるイメージ）
・Enemyクラス、Characterクラスにクリーチャー情報がありますが、同じであればBattleCreatureクラスに実装でよいかと。
・BattleControllerについて
　Webアプリケーションは通常複数ユーザが同時に使用することを想定して作成します。その際にコントローラクラスのメンバ変数は全てのユーザで共有してしまうので、ここでのゲーム情報（入力したキャラクター情報など）はコントローラクラスのメンバ変数としては設定してはいけません。ユーザ毎に異なる情報はセッション（またはユーザID毎にDB）に保存する必要があります。

**Comment by HirokiMAEDA-TC** [comment]
> 大変遅くなりましたが以下、レビュー指摘になります。
> ・まずは動作的には問題ないです。一通り実装できていて素晴らしいです。
> ・ただ、作り方の点で指定と異なる点があります。
> 　職業に応じて戦士クラスや魔法使いクラスをインスタンス化していますが、それはキャラクター情報としてセッションに保存してください。（Characterクラスに名称のJobを持っていますが、それを置き換えるイメージ）
> ・Enemyクラス、Characterクラスにクリーチャー情報がありますが、同じであればBattleCreatureクラスに実装でよいかと。
> ・BattleControllerについて
> 　Webアプリケーションは通常複数ユーザが同時に使用することを想定して作成します。その際にコントローラクラスのメンバ変数は全てのユーザで共有してしまうので、ここでのゲーム情報（入力したキャラクター情報など）はコントローラクラスのメンバ変数としては設定してはいけません。ユーザ毎に異なる情報はセッション（またはユーザID毎にDB）に保存する必要があります。

**Comment by HirokiMAEDA-TC** [comment]
9月末で退社するため、研修を最後まで受講できないにも拘らず、貴重なお時間を使ってレビューをしていただきありがとうございます。

現在の業務では得られない、プログラミングの経験を積むことが出来たので、非常に為になりました。
Javaの文法だけでなく、HTMLやデータベースに触れることもでき、自分ひとりでは学習できないことも学べたこともありがたかったです。

抽象クラスの使い方やWebアプリの特徴(複数ユーザーが同時に使うこと)に関する理解をさらに深めることが必要だと感じました。
今回の経験を活かして、今後、開発業務にあたるように致します。

お手数をお掛けし申し訳ございません。
御多忙の中、お時間を割いていただきありがとうございました。
